version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: kata_php
    volumes:
      - ./kata-back:/var/www/html
    networks:
      - dev

  nginx:
    image: nginx:latest
    container_name: kata_nginx
    ports:
      - "8000:80"
    volumes:
      - ./kata-back:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dev
    
  db:
    image: mysql:8.0
    container_name: kata_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kata
      MYSQL_USER: kata
      MYSQL_PASSWORD: kata
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kata_pma
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db_data:
